[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sqlagent"
version = "0.1.0"
description = "A SQL agent for text-to-SQL tasks"

[tool.setuptools]
packages = ["sqlagent"]